In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
import statsmodels.api as sm

In [2]:
df=pd.read_csv('housing_price.csv')
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                  15         5612            1283   
1    -114.47     34.40                  19         7650            1901   
2    -114.56     33.69                  17          720             174   
3    -114.57     33.64                  14         1501             337   
4    -114.57     33.57                  20         1454             326   

   population  households  median_income  median_house_value  
0        1015         472         1.4936               66900  
1        1129         463         1.8200               80100  
2         333         117         1.6509               85700  
3         515         226         3.1917               73400  
4         624         262         1.9250               65500

In [3]:
df2=df.isnull().sum()
df2

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64

In [4]:
x=df.drop(columns='median_house_value').values
y=df.median_house_value.values
print('independent data\n',x)
print('dependenet data\n',y)

independent data
 [[-114.31     34.19     15.     ... 1015.      472.        1.4936]
 [-114.47     34.4      19.     ... 1129.      463.        1.82  ]
 [-114.56     33.69     17.     ...  333.      117.        1.6509]
 ...
 [-124.3      41.84     17.     ... 1244.      456.        3.0313]
 [-124.3      41.8      19.     ... 1298.      478.        1.9797]
 [-124.35     40.54     52.     ...  806.      270.        3.0147]]
dependenet data
 [ 66900  80100  85700 ... 103600  85800  94600]


In [5]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=10)

print('x_train and y_train dataset shape',x_train.shape,x_test.shape)
print('y_train and y_train dataset shape',y_train.shape,y_test.shape)

x_train and y_train dataset shape (13600, 8) (3400, 8)
y_train and y_train dataset shape (13600,) (3400,)


In [6]:
regressor=LinearRegression()
regressor.fit(x_train,y_train)


LinearRegression()

In [7]:
print('R2 value',regressor.score(x_test,y_test))
print('\n coefficient \n',regressor.coef_)
print('\n intercept',regressor.intercept_)


R2 value 0.6484403017760394

 coefficient 
 [-4.34225673e+04 -4.34584915e+04  1.15417922e+03 -8.34683693e+00
  1.14234465e+02 -3.87425498e+01  5.04252279e+01  4.02554220e+04]

 intercept -3635200.010897572


In [9]:
y_pred=regressor.predict(x_test)

In [10]:
pred=pd.DataFrame({'Actual':y_test,'Predicted':y_pred})
pred.head(10)

Actual      Predicted
0   96100   -8475.675202
1  500001  490876.394233
2  177200  112662.107990
3   55000  218093.753334
4  220800  207600.925885
5  158300  121540.170888
6   37900  180602.126583
7  115600  104694.108104
8  359700  310765.123759
9  203300  265864.990208

In [11]:
X2=sm.add_constant(x)
est=sm.OLS(y,X2)
est2=est.fit()
print(est2.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.641
Model:                            OLS   Adj. R-squared:                  0.641
Method:                 Least Squares   F-statistic:                     3798.
Date:                Fri, 02 Dec 2022   Prob (F-statistic):               0.00
Time:                        06:30:32   Log-Likelihood:            -2.1365e+05
No. Observations:               17000   AIC:                         4.273e+05
Df Residuals:                   16991   BIC:                         4.274e+05
Df Model:                           8                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -3.621e+06   6.92e+04    -52.312      0.0